name: semgrep-rules-test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test-latest:
    name: rules-test-latest
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    - name: install semgrep
      run: pip3 install semgrep
    - name: install pro-engine
      run: semgrep install-semgrep-pro
    - name: validate rules
      run: semgrep --validate --config ./solidity
    - name: run semgrep
      run: semgrep --test --pro --test-ignore-todo
    env: 
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}